/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author RAMA
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPengguna = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuDataSiswa = new javax.swing.JMenuItem();
        MenuDataGuru = new javax.swing.JMenuItem();
        MenuDataMataPelajaran = new javax.swing.JMenuItem();
        MenuDataKelas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuTransaksi = new javax.swing.JMenuItem();
        MenuCetakNotaPembayaran = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuInputNilaiSiswa = new javax.swing.JMenuItem();
        MenuCetakHasilNilaiSiswa = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuLaporanDataSiswa = new javax.swing.JMenuItem();
        MenuLaporanDataGuru = new javax.swing.JMenuItem();
        MenuLaporanDataNilai = new javax.swing.JMenuItem();
        MenuLaporanDataPembayaranSPP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jDesktopPane1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SMP ISLAM AL-ANSHOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEM INFORMASI AKADEMIK");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-small_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Jl Kebon Kaung, Ciriung, Kec. Cibinong, Kab. Bogor Prov. Jawa Barat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELAMAT DATANG DI APLIKASI");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68))
                    .addComponent(jLabel2)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(243, 243, 243))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)))
                .addGap(289, 289, 289))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1 - Sistem.png"))); // NOI18N
        jMenu1.setText("Sistem");

        MenuPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login2 (2).png"))); // NOI18N
        MenuPengguna.setText("Pengguna");
        MenuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPengguna);

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/No entry.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(Keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2 - Master.png"))); // NOI18N
        jMenu2.setText("Master Data");

        MenuDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/siswa-medium.png"))); // NOI18N
        MenuDataSiswa.setText("Data Siswa");
        MenuDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataSiswaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDataSiswa);

        MenuDataGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Isi-Kelas-medium.png"))); // NOI18N
        MenuDataGuru.setText("Data Guru");
        MenuDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataGuruActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDataGuru);

        MenuDataMataPelajaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Report-medium1.png"))); // NOI18N
        MenuDataMataPelajaran.setText("Data Mata Pelajaran");
        MenuDataMataPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataMataPelajaranActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDataMataPelajaran);

        MenuDataKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3 - Mahasiswa.png"))); // NOI18N
        MenuDataKelas.setText("Data Kelas");
        MenuDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataKelasActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDataKelas);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pembayaran-medium.png"))); // NOI18N
        jMenu4.setText("Pembayaran SPP");

        MenuTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bebansumbangan-medium.png"))); // NOI18N
        MenuTransaksi.setText("Transaksi");
        MenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTransaksiActionPerformed(evt);
            }
        });
        jMenu4.add(MenuTransaksi);

        MenuCetakNotaPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print.png"))); // NOI18N
        MenuCetakNotaPembayaran.setText("Cetak Nota Pembayaran");
        MenuCetakNotaPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCetakNotaPembayaranActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCetakNotaPembayaran);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/periode-medium.png"))); // NOI18N
        jMenu3.setText("Penilaian");

        MenuInputNilaiSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tutor_login_icon.png"))); // NOI18N
        MenuInputNilaiSiswa.setText("Input Nilai Siswa");
        MenuInputNilaiSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInputNilaiSiswaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuInputNilaiSiswa);

        MenuCetakHasilNilaiSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print.png"))); // NOI18N
        MenuCetakHasilNilaiSiswa.setText("Cetak Hasil Nilai Siswa");
        MenuCetakHasilNilaiSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCetakHasilNilaiSiswaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCetakHasilNilaiSiswa);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bebansumbangan-medium.png"))); // NOI18N
        jMenu5.setText("Laporan");

        MenuLaporanDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/siswa-medium.png"))); // NOI18N
        MenuLaporanDataSiswa.setText("Laporan Data Siswa");
        MenuLaporanDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanDataSiswaActionPerformed(evt);
            }
        });
        jMenu5.add(MenuLaporanDataSiswa);

        MenuLaporanDataGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Isi-Kelas-medium.png"))); // NOI18N
        MenuLaporanDataGuru.setText("Laporan Data Guru");
        MenuLaporanDataGuru.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MenuLaporanDataGuruAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        MenuLaporanDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanDataGuruActionPerformed(evt);
            }
        });
        jMenu5.add(MenuLaporanDataGuru);

        MenuLaporanDataNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Knowledge.png"))); // NOI18N
        MenuLaporanDataNilai.setText("Laporan Data Nilai");
        jMenu5.add(MenuLaporanDataNilai);

        MenuLaporanDataPembayaranSPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print.png"))); // NOI18N
        MenuLaporanDataPembayaranSPP.setText("Laporan Data Pembayaran SPP");
        MenuLaporanDataPembayaranSPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanDataPembayaranSPPActionPerformed(evt);
            }
        });
        jMenu5.add(MenuLaporanDataPembayaranSPP);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataSiswaActionPerformed
        // TODO add your handling code here:
        IfrDaftarSiswa ipb = null;
        try {
            ipb = new IfrDaftarSiswa();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuDataSiswaActionPerformed

    private void MenuDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataGuruActionPerformed
        // TODO add your handling code here:
        IfrDaftarGuru ipb = null;
        try {
            ipb = new IfrDaftarGuru();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuDataGuruActionPerformed

    private void MenuDataMataPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataMataPelajaranActionPerformed
        // TODO add your handling code here:
        IfrDaftarMataPelajaran ipb = null;
        ipb = new IfrDaftarMataPelajaran();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuDataMataPelajaranActionPerformed

    private void MenuDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataKelasActionPerformed
        // TODO add your handling code here:
        IfrDaftarKelas ipb = null;
        ipb = new IfrDaftarKelas();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuDataKelasActionPerformed

    private void MenuLaporanDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanDataGuruActionPerformed
        // TODO add your handling code here:
        IfrLaporanGuru ipb = null;
        ipb = new IfrLaporanGuru();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);

    }//GEN-LAST:event_MenuLaporanDataGuruActionPerformed

    private void MenuLaporanDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanDataSiswaActionPerformed
        // TODO add your handling code here:
        IfrLaporanSiswa ipb = null;
        ipb = new IfrLaporanSiswa();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuLaporanDataSiswaActionPerformed

    private void MenuLaporanDataGuruAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MenuLaporanDataGuruAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLaporanDataGuruAncestorAdded

    private void MenuInputNilaiSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInputNilaiSiswaActionPerformed
        // TODO add your handling code here:
        IfrDaftarNilai ipb = null;
        try {
            ipb = new IfrDaftarNilai();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuInputNilaiSiswaActionPerformed

    private void MenuCetakHasilNilaiSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCetakHasilNilaiSiswaActionPerformed
        // TODO add your handling code here:
        IfrHasiNilaiSiswa ipb = null;
        ipb = new IfrHasiNilaiSiswa();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuCetakHasilNilaiSiswaActionPerformed

    private void MenuLaporanDataPembayaranSPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanDataPembayaranSPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLaporanDataPembayaranSPPActionPerformed

    private void MenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTransaksiActionPerformed
        // TODO add your handling code here:
        IfrBayarSPP ipb = null;
        ipb = new IfrBayarSPP();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuTransaksiActionPerformed

    private void MenuCetakNotaPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCetakNotaPembayaranActionPerformed
        // TODO add your handling code here:
        IfrDataPembayaranSPP ipb = null;
        try {
            ipb = new IfrDataPembayaranSPP();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuCetakNotaPembayaranActionPerformed

    private void MenuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenggunaActionPerformed
        // TODO add your handling code here:
        IfrDaftarPengguna ipb = null;
        ipb = new IfrDaftarPengguna();
        jDesktopPane1.add(ipb);
        ipb.setVisible(true);
    }//GEN-LAST:event_MenuPenggunaActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        FrLogin dd=new FrLogin();
        dd.setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem MenuCetakHasilNilaiSiswa;
    private javax.swing.JMenuItem MenuCetakNotaPembayaran;
    private javax.swing.JMenuItem MenuDataGuru;
    private javax.swing.JMenuItem MenuDataKelas;
    private javax.swing.JMenuItem MenuDataMataPelajaran;
    private javax.swing.JMenuItem MenuDataSiswa;
    private javax.swing.JMenuItem MenuInputNilaiSiswa;
    private javax.swing.JMenuItem MenuLaporanDataGuru;
    private javax.swing.JMenuItem MenuLaporanDataNilai;
    private javax.swing.JMenuItem MenuLaporanDataPembayaranSPP;
    private javax.swing.JMenuItem MenuLaporanDataSiswa;
    private javax.swing.JMenuItem MenuPengguna;
    private javax.swing.JMenuItem MenuTransaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
